use_frameworks!

target 'ScrollingNavbarDemo' do
  pod 'AMScrollingNavbar', path: '../'
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

target 'ScrollingNavbarDemoTests' do
  pod 'AMScrollingNavbar', path: '../'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'xcode7.1'
  pod 'Quick', :git => 'https://github.com/andreamazz/Quick.git', :branch => 'xcode7.1'
  pod 'Nimble-Snapshots'
end

