use_frameworks!
platform :ios, '8.0'

target 'ScrollingNavbarDemo' do
  pod 'AMScrollingNavbar', path: '../'
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

target 'ScrollingNavbarDemoTests' do
  pod 'AMScrollingNavbar', path: '../'
  pod 'Nimble', '~> 4.0.1'
  pod 'Quick', '~> 0.9.2'
  pod 'Nimble-Snapshots'
end

