use_frameworks!

target 'ScrollingNavbarDemo' do
  pod 'AMScrollingNavbar', path: '../'
end

target 'ScrollingNavbarDemoTests' do
  pod 'AMScrollingNavbar', path: '../'
  pod 'Nimble', '~> 0.4.0'
  pod 'Quick', '~> 0.3.1'
  pod 'Nimble-Snapshots', '~> 0.4.0'
end

